version: '3.9'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code:/app
    ports:
      - 8000:8000

    environment:
      - "DJANGO_SECRET_KEY='django-insecure-rfs7ycl5s9_bw87m)u2ndngnz)fbwr&o92v62wxs-zm#brcq#u'"
      - "DJANGO_DEBUG=True"